version: '3'
services:
  backend:
    image: <your-dockerhub-username>/courses-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend-network

  frontend:
    image: <your-dockerhub-username>/courses-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-network

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: courses
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend-network

networks:
  backend-network:


For Testing you can run docker-compose up to start the applications and test them locally. 
